services:
    samba:
        container_name: samba
        ports:
            - "${SMB_PORT}:445"
        restart: unless-stopped
        volumes:
            - ${SMB_DATAPATH}:/samba/data:Z
        environment:
            SMB_USERNAME: ${SMB_USERNAME}
            SMB_USERPASSWD: ${SMB_USERPASSWD}
            SMB_UID: ${SMB_UID}
            SMB_GID: ${SMB_GID}
        image: ghcr.io/cho0h5/build-samba-container:main
